### ISSUE TITLE
Performance differences with Ranklib

### ISSUE THREAD

**Issue by seyyaw** [o19s/RankyMcRankFace#9]
Hi the RankyMCRankFace group!

I like the fact that you mavenize and continue improving the Ranklib tool.
I found a huge impovement in the running time during training. But there is a larger difference in performance, in the following metrics I have tried (**MAP**, **P@K**, and **NDCG@K**).
Is this becuase the old calculations were wrong or you have changed the core of the training?

Thanks

**Comment by softwaredoug** [comment]
Thanks @seyyaw -- That's perhaps concerning! We have not really changed anything at the core. The speed upticks are mostly around serializing and deserializing models. I'm curious if you have an example (like a set of training data) that shows this issue?

**Comment by seyyaw** [comment]
@softwaredoug Thank you for your prompt response
I just tried with the dataset from https://onedrive.live.com/?authkey=%21ACnoZZSZVfHPJd0&id=8FEADC23D838BDA8%21107&cid=8FEADC23D838BDA8 (with MQ2008.rar dold1/train.txt and Fold1/test.txt). Here the difference is not so prnounced (at least on test). Example (**_Ranklib 2.1 MAP_** (**train 0.7009, Test 0.4279**), **_RankyMcRankFace 0.2.0 Map_** (**tarin 0.5907, test 0.424**))
For my data set on Test (**_Ranklib 2.1 MAP_** (**Test 0.8782**), **_RankyMcRankFace 0.2.0 Map_** (**Test 0.9053**)), Unfortunately I could not share the dataset now.

**Comment by seyyaw** [comment]
I tested against the Ranklib2.9 release (which I were not aware of)  and I have the same result with RankyMCRankFace. Closing the issue then.
